spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root

server:
  port: 8081


dubbo:
  application:
    name: customer
  registry:
    address: zookeeper://127.0.0.1:2181